add sonar-scanner-cli
cloudkite-io/cloudbuild-docker-images pull request #29
Opened 2023-09-12 16:17 UTC by TeamoreA

2023-09-12 18:51 UTC, victortrac commented
Please take the time to explain why this is needed.

2023-09-12 19:51 UTC, TeamoreA commented
> Please take the time to explain why this is needed.

I have added a README

2023-09-12 21:24 UTC, victortrac requested changes

2023-09-12 21:24 UTC, victortrac commented on sonar-scanner-cli/README.md
> + This image helps us to keep a copy of `sonarsource/sonar-scanner-cli` docker image in our CK library and also add additional packages to it. Currently, we only have `sudo` added.
This comment only says *what* you have done, which is self-evident from the code.  The question is *why* you need to add sudo.

2023-09-13 16:41 UTC, TeamoreA commented on sonar-scanner-cli/README.md
> + This image helps us to keep a copy of `sonarsource/sonar-scanner-cli` docker image in our CK library and also add additional packages to it. Currently, we only have `sudo` added.
I have added more details as to why we need sudo. Please review.

2023-09-13 20:49 UTC, victortrac approved these changes

2023-09-14 11:04 UTC, merged